# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/clion/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /opt/clion/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /media/eik/DATEN/phd/repository/research/Graz2019/code/spn-transition-probability

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /media/eik/DATEN/phd/repository/research/Graz2019/code/spn-transition-probability

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/clion/bin/cmake/linux/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/opt/clion/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /media/eik/DATEN/phd/repository/research/Graz2019/code/spn-transition-probability/CMakeFiles /media/eik/DATEN/phd/repository/research/Graz2019/code/spn-transition-probability/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /media/eik/DATEN/phd/repository/research/Graz2019/code/spn-transition-probability/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_byte_pattern_generator

# Build rule for target.
test_byte_pattern_generator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_byte_pattern_generator
.PHONY : test_byte_pattern_generator

# fast build rule for target.
test_byte_pattern_generator/fast:
	$(MAKE) -f CMakeFiles/test_byte_pattern_generator.dir/build.make CMakeFiles/test_byte_pattern_generator.dir/build
.PHONY : test_byte_pattern_generator/fast

#=============================================================================
# Target rules for targets named test_aes_row_and_column_transition_algorithm

# Build rule for target.
test_aes_row_and_column_transition_algorithm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_aes_row_and_column_transition_algorithm
.PHONY : test_aes_row_and_column_transition_algorithm

# fast build rule for target.
test_aes_row_and_column_transition_algorithm/fast:
	$(MAKE) -f CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/build
.PHONY : test_aes_row_and_column_transition_algorithm/fast

#=============================================================================
# Target rules for targets named test_many_aes_column_transitions

# Build rule for target.
test_many_aes_column_transitions: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_many_aes_column_transitions
.PHONY : test_many_aes_column_transitions

# fast build rule for target.
test_many_aes_column_transitions/fast:
	$(MAKE) -f CMakeFiles/test_many_aes_column_transitions.dir/build.make CMakeFiles/test_many_aes_column_transitions.dir/build
.PHONY : test_many_aes_column_transitions/fast

#=============================================================================
# Target rules for targets named test_aes_column_transition_algorithm

# Build rule for target.
test_aes_column_transition_algorithm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_aes_column_transition_algorithm
.PHONY : test_aes_column_transition_algorithm

# fast build rule for target.
test_aes_column_transition_algorithm/fast:
	$(MAKE) -f CMakeFiles/test_aes_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_column_transition_algorithm.dir/build
.PHONY : test_aes_column_transition_algorithm/fast

#=============================================================================
# Target rules for targets named test_aes_byte_transition_algorithm

# Build rule for target.
test_aes_byte_transition_algorithm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_aes_byte_transition_algorithm
.PHONY : test_aes_byte_transition_algorithm

# fast build rule for target.
test_aes_byte_transition_algorithm/fast:
	$(MAKE) -f CMakeFiles/test_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_aes_byte_transition_algorithm.dir/build
.PHONY : test_aes_byte_transition_algorithm/fast

#=============================================================================
# Target rules for targets named test_all_small_aes_column_transitions

# Build rule for target.
test_all_small_aes_column_transitions: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_all_small_aes_column_transitions
.PHONY : test_all_small_aes_column_transitions

# fast build rule for target.
test_all_small_aes_column_transitions/fast:
	$(MAKE) -f CMakeFiles/test_all_small_aes_column_transitions.dir/build.make CMakeFiles/test_all_small_aes_column_transitions.dir/build
.PHONY : test_all_small_aes_column_transitions/fast

#=============================================================================
# Target rules for targets named test_all_aes_column_transitions

# Build rule for target.
test_all_aes_column_transitions: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_all_aes_column_transitions
.PHONY : test_all_aes_column_transitions

# fast build rule for target.
test_all_aes_column_transitions/fast:
	$(MAKE) -f CMakeFiles/test_all_aes_column_transitions.dir/build.make CMakeFiles/test_all_aes_column_transitions.dir/build
.PHONY : test_all_aes_column_transitions/fast

#=============================================================================
# Target rules for targets named transition_matrix

# Build rule for target.
transition_matrix: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 transition_matrix
.PHONY : transition_matrix

# fast build rule for target.
transition_matrix/fast:
	$(MAKE) -f CMakeFiles/transition_matrix.dir/build.make CMakeFiles/transition_matrix.dir/build
.PHONY : transition_matrix/fast

#=============================================================================
# Target rules for targets named test_all_aes_byte_transitions

# Build rule for target.
test_all_aes_byte_transitions: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_all_aes_byte_transitions
.PHONY : test_all_aes_byte_transitions

# fast build rule for target.
test_all_aes_byte_transitions/fast:
	$(MAKE) -f CMakeFiles/test_all_aes_byte_transitions.dir/build.make CMakeFiles/test_all_aes_byte_transitions.dir/build
.PHONY : test_all_aes_byte_transitions/fast

#=============================================================================
# Target rules for targets named test_small_aes_byte_transition_algorithm

# Build rule for target.
test_small_aes_byte_transition_algorithm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_small_aes_byte_transition_algorithm
.PHONY : test_small_aes_byte_transition_algorithm

# fast build rule for target.
test_small_aes_byte_transition_algorithm/fast:
	$(MAKE) -f CMakeFiles/test_small_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_small_aes_byte_transition_algorithm.dir/build
.PHONY : test_small_aes_byte_transition_algorithm/fast

#=============================================================================
# Target rules for targets named test_many_small_aes_column_transitions

# Build rule for target.
test_many_small_aes_column_transitions: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_many_small_aes_column_transitions
.PHONY : test_many_small_aes_column_transitions

# fast build rule for target.
test_many_small_aes_column_transitions/fast:
	$(MAKE) -f CMakeFiles/test_many_small_aes_column_transitions.dir/build.make CMakeFiles/test_many_small_aes_column_transitions.dir/build
.PHONY : test_many_small_aes_column_transitions/fast

#=============================================================================
# Target rules for targets named test_all_small_aes_byte_transitions

# Build rule for target.
test_all_small_aes_byte_transitions: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_all_small_aes_byte_transitions
.PHONY : test_all_small_aes_byte_transitions

# fast build rule for target.
test_all_small_aes_byte_transitions/fast:
	$(MAKE) -f CMakeFiles/test_all_small_aes_byte_transitions.dir/build.make CMakeFiles/test_all_small_aes_byte_transitions.dir/build
.PHONY : test_all_small_aes_byte_transitions/fast

src/aes_byte_transition_algorithm.o: src/aes_byte_transition_algorithm.cc.o

.PHONY : src/aes_byte_transition_algorithm.o

# target to build an object file
src/aes_byte_transition_algorithm.cc.o:
	$(MAKE) -f CMakeFiles/test_byte_pattern_generator.dir/build.make CMakeFiles/test_byte_pattern_generator.dir/src/aes_byte_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/src/aes_byte_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/test_many_aes_column_transitions.dir/build.make CMakeFiles/test_many_aes_column_transitions.dir/src/aes_byte_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/test_aes_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_column_transition_algorithm.dir/src/aes_byte_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/test_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_aes_byte_transition_algorithm.dir/src/aes_byte_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/test_all_small_aes_column_transitions.dir/build.make CMakeFiles/test_all_small_aes_column_transitions.dir/src/aes_byte_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/test_all_aes_column_transitions.dir/build.make CMakeFiles/test_all_aes_column_transitions.dir/src/aes_byte_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/transition_matrix.dir/build.make CMakeFiles/transition_matrix.dir/src/aes_byte_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/test_all_aes_byte_transitions.dir/build.make CMakeFiles/test_all_aes_byte_transitions.dir/src/aes_byte_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/test_small_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_small_aes_byte_transition_algorithm.dir/src/aes_byte_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/test_many_small_aes_column_transitions.dir/build.make CMakeFiles/test_many_small_aes_column_transitions.dir/src/aes_byte_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/test_all_small_aes_byte_transitions.dir/build.make CMakeFiles/test_all_small_aes_byte_transitions.dir/src/aes_byte_transition_algorithm.cc.o
.PHONY : src/aes_byte_transition_algorithm.cc.o

src/aes_byte_transition_algorithm.i: src/aes_byte_transition_algorithm.cc.i

.PHONY : src/aes_byte_transition_algorithm.i

# target to preprocess a source file
src/aes_byte_transition_algorithm.cc.i:
	$(MAKE) -f CMakeFiles/test_byte_pattern_generator.dir/build.make CMakeFiles/test_byte_pattern_generator.dir/src/aes_byte_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/src/aes_byte_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/test_many_aes_column_transitions.dir/build.make CMakeFiles/test_many_aes_column_transitions.dir/src/aes_byte_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/test_aes_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_column_transition_algorithm.dir/src/aes_byte_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/test_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_aes_byte_transition_algorithm.dir/src/aes_byte_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/test_all_small_aes_column_transitions.dir/build.make CMakeFiles/test_all_small_aes_column_transitions.dir/src/aes_byte_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/test_all_aes_column_transitions.dir/build.make CMakeFiles/test_all_aes_column_transitions.dir/src/aes_byte_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/transition_matrix.dir/build.make CMakeFiles/transition_matrix.dir/src/aes_byte_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/test_all_aes_byte_transitions.dir/build.make CMakeFiles/test_all_aes_byte_transitions.dir/src/aes_byte_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/test_small_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_small_aes_byte_transition_algorithm.dir/src/aes_byte_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/test_many_small_aes_column_transitions.dir/build.make CMakeFiles/test_many_small_aes_column_transitions.dir/src/aes_byte_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/test_all_small_aes_byte_transitions.dir/build.make CMakeFiles/test_all_small_aes_byte_transitions.dir/src/aes_byte_transition_algorithm.cc.i
.PHONY : src/aes_byte_transition_algorithm.cc.i

src/aes_byte_transition_algorithm.s: src/aes_byte_transition_algorithm.cc.s

.PHONY : src/aes_byte_transition_algorithm.s

# target to generate assembly for a file
src/aes_byte_transition_algorithm.cc.s:
	$(MAKE) -f CMakeFiles/test_byte_pattern_generator.dir/build.make CMakeFiles/test_byte_pattern_generator.dir/src/aes_byte_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/src/aes_byte_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/test_many_aes_column_transitions.dir/build.make CMakeFiles/test_many_aes_column_transitions.dir/src/aes_byte_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/test_aes_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_column_transition_algorithm.dir/src/aes_byte_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/test_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_aes_byte_transition_algorithm.dir/src/aes_byte_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/test_all_small_aes_column_transitions.dir/build.make CMakeFiles/test_all_small_aes_column_transitions.dir/src/aes_byte_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/test_all_aes_column_transitions.dir/build.make CMakeFiles/test_all_aes_column_transitions.dir/src/aes_byte_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/transition_matrix.dir/build.make CMakeFiles/transition_matrix.dir/src/aes_byte_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/test_all_aes_byte_transitions.dir/build.make CMakeFiles/test_all_aes_byte_transitions.dir/src/aes_byte_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/test_small_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_small_aes_byte_transition_algorithm.dir/src/aes_byte_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/test_many_small_aes_column_transitions.dir/build.make CMakeFiles/test_many_small_aes_column_transitions.dir/src/aes_byte_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/test_all_small_aes_byte_transitions.dir/build.make CMakeFiles/test_all_small_aes_byte_transitions.dir/src/aes_byte_transition_algorithm.cc.s
.PHONY : src/aes_byte_transition_algorithm.cc.s

src/aes_column_transition_algorithm.o: src/aes_column_transition_algorithm.cc.o

.PHONY : src/aes_column_transition_algorithm.o

# target to build an object file
src/aes_column_transition_algorithm.cc.o:
	$(MAKE) -f CMakeFiles/test_byte_pattern_generator.dir/build.make CMakeFiles/test_byte_pattern_generator.dir/src/aes_column_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/src/aes_column_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/test_many_aes_column_transitions.dir/build.make CMakeFiles/test_many_aes_column_transitions.dir/src/aes_column_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/test_aes_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_column_transition_algorithm.dir/src/aes_column_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/test_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_aes_byte_transition_algorithm.dir/src/aes_column_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/test_all_small_aes_column_transitions.dir/build.make CMakeFiles/test_all_small_aes_column_transitions.dir/src/aes_column_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/test_all_aes_column_transitions.dir/build.make CMakeFiles/test_all_aes_column_transitions.dir/src/aes_column_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/transition_matrix.dir/build.make CMakeFiles/transition_matrix.dir/src/aes_column_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/test_all_aes_byte_transitions.dir/build.make CMakeFiles/test_all_aes_byte_transitions.dir/src/aes_column_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/test_small_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_small_aes_byte_transition_algorithm.dir/src/aes_column_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/test_many_small_aes_column_transitions.dir/build.make CMakeFiles/test_many_small_aes_column_transitions.dir/src/aes_column_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/test_all_small_aes_byte_transitions.dir/build.make CMakeFiles/test_all_small_aes_byte_transitions.dir/src/aes_column_transition_algorithm.cc.o
.PHONY : src/aes_column_transition_algorithm.cc.o

src/aes_column_transition_algorithm.i: src/aes_column_transition_algorithm.cc.i

.PHONY : src/aes_column_transition_algorithm.i

# target to preprocess a source file
src/aes_column_transition_algorithm.cc.i:
	$(MAKE) -f CMakeFiles/test_byte_pattern_generator.dir/build.make CMakeFiles/test_byte_pattern_generator.dir/src/aes_column_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/src/aes_column_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/test_many_aes_column_transitions.dir/build.make CMakeFiles/test_many_aes_column_transitions.dir/src/aes_column_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/test_aes_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_column_transition_algorithm.dir/src/aes_column_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/test_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_aes_byte_transition_algorithm.dir/src/aes_column_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/test_all_small_aes_column_transitions.dir/build.make CMakeFiles/test_all_small_aes_column_transitions.dir/src/aes_column_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/test_all_aes_column_transitions.dir/build.make CMakeFiles/test_all_aes_column_transitions.dir/src/aes_column_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/transition_matrix.dir/build.make CMakeFiles/transition_matrix.dir/src/aes_column_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/test_all_aes_byte_transitions.dir/build.make CMakeFiles/test_all_aes_byte_transitions.dir/src/aes_column_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/test_small_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_small_aes_byte_transition_algorithm.dir/src/aes_column_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/test_many_small_aes_column_transitions.dir/build.make CMakeFiles/test_many_small_aes_column_transitions.dir/src/aes_column_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/test_all_small_aes_byte_transitions.dir/build.make CMakeFiles/test_all_small_aes_byte_transitions.dir/src/aes_column_transition_algorithm.cc.i
.PHONY : src/aes_column_transition_algorithm.cc.i

src/aes_column_transition_algorithm.s: src/aes_column_transition_algorithm.cc.s

.PHONY : src/aes_column_transition_algorithm.s

# target to generate assembly for a file
src/aes_column_transition_algorithm.cc.s:
	$(MAKE) -f CMakeFiles/test_byte_pattern_generator.dir/build.make CMakeFiles/test_byte_pattern_generator.dir/src/aes_column_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/src/aes_column_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/test_many_aes_column_transitions.dir/build.make CMakeFiles/test_many_aes_column_transitions.dir/src/aes_column_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/test_aes_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_column_transition_algorithm.dir/src/aes_column_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/test_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_aes_byte_transition_algorithm.dir/src/aes_column_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/test_all_small_aes_column_transitions.dir/build.make CMakeFiles/test_all_small_aes_column_transitions.dir/src/aes_column_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/test_all_aes_column_transitions.dir/build.make CMakeFiles/test_all_aes_column_transitions.dir/src/aes_column_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/transition_matrix.dir/build.make CMakeFiles/transition_matrix.dir/src/aes_column_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/test_all_aes_byte_transitions.dir/build.make CMakeFiles/test_all_aes_byte_transitions.dir/src/aes_column_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/test_small_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_small_aes_byte_transition_algorithm.dir/src/aes_column_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/test_many_small_aes_column_transitions.dir/build.make CMakeFiles/test_many_small_aes_column_transitions.dir/src/aes_column_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/test_all_small_aes_byte_transitions.dir/build.make CMakeFiles/test_all_small_aes_byte_transitions.dir/src/aes_column_transition_algorithm.cc.s
.PHONY : src/aes_column_transition_algorithm.cc.s

src/aes_row_and_column_transition_algorithm.o: src/aes_row_and_column_transition_algorithm.cc.o

.PHONY : src/aes_row_and_column_transition_algorithm.o

# target to build an object file
src/aes_row_and_column_transition_algorithm.cc.o:
	$(MAKE) -f CMakeFiles/test_byte_pattern_generator.dir/build.make CMakeFiles/test_byte_pattern_generator.dir/src/aes_row_and_column_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/src/aes_row_and_column_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/test_many_aes_column_transitions.dir/build.make CMakeFiles/test_many_aes_column_transitions.dir/src/aes_row_and_column_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/test_aes_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_column_transition_algorithm.dir/src/aes_row_and_column_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/test_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_aes_byte_transition_algorithm.dir/src/aes_row_and_column_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/test_all_small_aes_column_transitions.dir/build.make CMakeFiles/test_all_small_aes_column_transitions.dir/src/aes_row_and_column_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/test_all_aes_column_transitions.dir/build.make CMakeFiles/test_all_aes_column_transitions.dir/src/aes_row_and_column_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/transition_matrix.dir/build.make CMakeFiles/transition_matrix.dir/src/aes_row_and_column_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/test_all_aes_byte_transitions.dir/build.make CMakeFiles/test_all_aes_byte_transitions.dir/src/aes_row_and_column_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/test_small_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_small_aes_byte_transition_algorithm.dir/src/aes_row_and_column_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/test_many_small_aes_column_transitions.dir/build.make CMakeFiles/test_many_small_aes_column_transitions.dir/src/aes_row_and_column_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/test_all_small_aes_byte_transitions.dir/build.make CMakeFiles/test_all_small_aes_byte_transitions.dir/src/aes_row_and_column_transition_algorithm.cc.o
.PHONY : src/aes_row_and_column_transition_algorithm.cc.o

src/aes_row_and_column_transition_algorithm.i: src/aes_row_and_column_transition_algorithm.cc.i

.PHONY : src/aes_row_and_column_transition_algorithm.i

# target to preprocess a source file
src/aes_row_and_column_transition_algorithm.cc.i:
	$(MAKE) -f CMakeFiles/test_byte_pattern_generator.dir/build.make CMakeFiles/test_byte_pattern_generator.dir/src/aes_row_and_column_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/src/aes_row_and_column_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/test_many_aes_column_transitions.dir/build.make CMakeFiles/test_many_aes_column_transitions.dir/src/aes_row_and_column_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/test_aes_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_column_transition_algorithm.dir/src/aes_row_and_column_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/test_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_aes_byte_transition_algorithm.dir/src/aes_row_and_column_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/test_all_small_aes_column_transitions.dir/build.make CMakeFiles/test_all_small_aes_column_transitions.dir/src/aes_row_and_column_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/test_all_aes_column_transitions.dir/build.make CMakeFiles/test_all_aes_column_transitions.dir/src/aes_row_and_column_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/transition_matrix.dir/build.make CMakeFiles/transition_matrix.dir/src/aes_row_and_column_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/test_all_aes_byte_transitions.dir/build.make CMakeFiles/test_all_aes_byte_transitions.dir/src/aes_row_and_column_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/test_small_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_small_aes_byte_transition_algorithm.dir/src/aes_row_and_column_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/test_many_small_aes_column_transitions.dir/build.make CMakeFiles/test_many_small_aes_column_transitions.dir/src/aes_row_and_column_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/test_all_small_aes_byte_transitions.dir/build.make CMakeFiles/test_all_small_aes_byte_transitions.dir/src/aes_row_and_column_transition_algorithm.cc.i
.PHONY : src/aes_row_and_column_transition_algorithm.cc.i

src/aes_row_and_column_transition_algorithm.s: src/aes_row_and_column_transition_algorithm.cc.s

.PHONY : src/aes_row_and_column_transition_algorithm.s

# target to generate assembly for a file
src/aes_row_and_column_transition_algorithm.cc.s:
	$(MAKE) -f CMakeFiles/test_byte_pattern_generator.dir/build.make CMakeFiles/test_byte_pattern_generator.dir/src/aes_row_and_column_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/src/aes_row_and_column_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/test_many_aes_column_transitions.dir/build.make CMakeFiles/test_many_aes_column_transitions.dir/src/aes_row_and_column_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/test_aes_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_column_transition_algorithm.dir/src/aes_row_and_column_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/test_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_aes_byte_transition_algorithm.dir/src/aes_row_and_column_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/test_all_small_aes_column_transitions.dir/build.make CMakeFiles/test_all_small_aes_column_transitions.dir/src/aes_row_and_column_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/test_all_aes_column_transitions.dir/build.make CMakeFiles/test_all_aes_column_transitions.dir/src/aes_row_and_column_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/transition_matrix.dir/build.make CMakeFiles/transition_matrix.dir/src/aes_row_and_column_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/test_all_aes_byte_transitions.dir/build.make CMakeFiles/test_all_aes_byte_transitions.dir/src/aes_row_and_column_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/test_small_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_small_aes_byte_transition_algorithm.dir/src/aes_row_and_column_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/test_many_small_aes_column_transitions.dir/build.make CMakeFiles/test_many_small_aes_column_transitions.dir/src/aes_row_and_column_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/test_all_small_aes_byte_transitions.dir/build.make CMakeFiles/test_all_small_aes_byte_transitions.dir/src/aes_row_and_column_transition_algorithm.cc.s
.PHONY : src/aes_row_and_column_transition_algorithm.cc.s

src/byte_pattern_generator.o: src/byte_pattern_generator.cc.o

.PHONY : src/byte_pattern_generator.o

# target to build an object file
src/byte_pattern_generator.cc.o:
	$(MAKE) -f CMakeFiles/test_byte_pattern_generator.dir/build.make CMakeFiles/test_byte_pattern_generator.dir/src/byte_pattern_generator.cc.o
	$(MAKE) -f CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/src/byte_pattern_generator.cc.o
	$(MAKE) -f CMakeFiles/test_many_aes_column_transitions.dir/build.make CMakeFiles/test_many_aes_column_transitions.dir/src/byte_pattern_generator.cc.o
	$(MAKE) -f CMakeFiles/test_aes_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_column_transition_algorithm.dir/src/byte_pattern_generator.cc.o
	$(MAKE) -f CMakeFiles/test_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_aes_byte_transition_algorithm.dir/src/byte_pattern_generator.cc.o
	$(MAKE) -f CMakeFiles/test_all_small_aes_column_transitions.dir/build.make CMakeFiles/test_all_small_aes_column_transitions.dir/src/byte_pattern_generator.cc.o
	$(MAKE) -f CMakeFiles/test_all_aes_column_transitions.dir/build.make CMakeFiles/test_all_aes_column_transitions.dir/src/byte_pattern_generator.cc.o
	$(MAKE) -f CMakeFiles/transition_matrix.dir/build.make CMakeFiles/transition_matrix.dir/src/byte_pattern_generator.cc.o
	$(MAKE) -f CMakeFiles/test_all_aes_byte_transitions.dir/build.make CMakeFiles/test_all_aes_byte_transitions.dir/src/byte_pattern_generator.cc.o
	$(MAKE) -f CMakeFiles/test_small_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_small_aes_byte_transition_algorithm.dir/src/byte_pattern_generator.cc.o
	$(MAKE) -f CMakeFiles/test_many_small_aes_column_transitions.dir/build.make CMakeFiles/test_many_small_aes_column_transitions.dir/src/byte_pattern_generator.cc.o
	$(MAKE) -f CMakeFiles/test_all_small_aes_byte_transitions.dir/build.make CMakeFiles/test_all_small_aes_byte_transitions.dir/src/byte_pattern_generator.cc.o
.PHONY : src/byte_pattern_generator.cc.o

src/byte_pattern_generator.i: src/byte_pattern_generator.cc.i

.PHONY : src/byte_pattern_generator.i

# target to preprocess a source file
src/byte_pattern_generator.cc.i:
	$(MAKE) -f CMakeFiles/test_byte_pattern_generator.dir/build.make CMakeFiles/test_byte_pattern_generator.dir/src/byte_pattern_generator.cc.i
	$(MAKE) -f CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/src/byte_pattern_generator.cc.i
	$(MAKE) -f CMakeFiles/test_many_aes_column_transitions.dir/build.make CMakeFiles/test_many_aes_column_transitions.dir/src/byte_pattern_generator.cc.i
	$(MAKE) -f CMakeFiles/test_aes_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_column_transition_algorithm.dir/src/byte_pattern_generator.cc.i
	$(MAKE) -f CMakeFiles/test_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_aes_byte_transition_algorithm.dir/src/byte_pattern_generator.cc.i
	$(MAKE) -f CMakeFiles/test_all_small_aes_column_transitions.dir/build.make CMakeFiles/test_all_small_aes_column_transitions.dir/src/byte_pattern_generator.cc.i
	$(MAKE) -f CMakeFiles/test_all_aes_column_transitions.dir/build.make CMakeFiles/test_all_aes_column_transitions.dir/src/byte_pattern_generator.cc.i
	$(MAKE) -f CMakeFiles/transition_matrix.dir/build.make CMakeFiles/transition_matrix.dir/src/byte_pattern_generator.cc.i
	$(MAKE) -f CMakeFiles/test_all_aes_byte_transitions.dir/build.make CMakeFiles/test_all_aes_byte_transitions.dir/src/byte_pattern_generator.cc.i
	$(MAKE) -f CMakeFiles/test_small_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_small_aes_byte_transition_algorithm.dir/src/byte_pattern_generator.cc.i
	$(MAKE) -f CMakeFiles/test_many_small_aes_column_transitions.dir/build.make CMakeFiles/test_many_small_aes_column_transitions.dir/src/byte_pattern_generator.cc.i
	$(MAKE) -f CMakeFiles/test_all_small_aes_byte_transitions.dir/build.make CMakeFiles/test_all_small_aes_byte_transitions.dir/src/byte_pattern_generator.cc.i
.PHONY : src/byte_pattern_generator.cc.i

src/byte_pattern_generator.s: src/byte_pattern_generator.cc.s

.PHONY : src/byte_pattern_generator.s

# target to generate assembly for a file
src/byte_pattern_generator.cc.s:
	$(MAKE) -f CMakeFiles/test_byte_pattern_generator.dir/build.make CMakeFiles/test_byte_pattern_generator.dir/src/byte_pattern_generator.cc.s
	$(MAKE) -f CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/src/byte_pattern_generator.cc.s
	$(MAKE) -f CMakeFiles/test_many_aes_column_transitions.dir/build.make CMakeFiles/test_many_aes_column_transitions.dir/src/byte_pattern_generator.cc.s
	$(MAKE) -f CMakeFiles/test_aes_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_column_transition_algorithm.dir/src/byte_pattern_generator.cc.s
	$(MAKE) -f CMakeFiles/test_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_aes_byte_transition_algorithm.dir/src/byte_pattern_generator.cc.s
	$(MAKE) -f CMakeFiles/test_all_small_aes_column_transitions.dir/build.make CMakeFiles/test_all_small_aes_column_transitions.dir/src/byte_pattern_generator.cc.s
	$(MAKE) -f CMakeFiles/test_all_aes_column_transitions.dir/build.make CMakeFiles/test_all_aes_column_transitions.dir/src/byte_pattern_generator.cc.s
	$(MAKE) -f CMakeFiles/transition_matrix.dir/build.make CMakeFiles/transition_matrix.dir/src/byte_pattern_generator.cc.s
	$(MAKE) -f CMakeFiles/test_all_aes_byte_transitions.dir/build.make CMakeFiles/test_all_aes_byte_transitions.dir/src/byte_pattern_generator.cc.s
	$(MAKE) -f CMakeFiles/test_small_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_small_aes_byte_transition_algorithm.dir/src/byte_pattern_generator.cc.s
	$(MAKE) -f CMakeFiles/test_many_small_aes_column_transitions.dir/build.make CMakeFiles/test_many_small_aes_column_transitions.dir/src/byte_pattern_generator.cc.s
	$(MAKE) -f CMakeFiles/test_all_small_aes_byte_transitions.dir/build.make CMakeFiles/test_all_small_aes_byte_transitions.dir/src/byte_pattern_generator.cc.s
.PHONY : src/byte_pattern_generator.cc.s

src/column_pattern_generator.o: src/column_pattern_generator.cc.o

.PHONY : src/column_pattern_generator.o

# target to build an object file
src/column_pattern_generator.cc.o:
	$(MAKE) -f CMakeFiles/test_byte_pattern_generator.dir/build.make CMakeFiles/test_byte_pattern_generator.dir/src/column_pattern_generator.cc.o
	$(MAKE) -f CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/src/column_pattern_generator.cc.o
	$(MAKE) -f CMakeFiles/test_many_aes_column_transitions.dir/build.make CMakeFiles/test_many_aes_column_transitions.dir/src/column_pattern_generator.cc.o
	$(MAKE) -f CMakeFiles/test_aes_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_column_transition_algorithm.dir/src/column_pattern_generator.cc.o
	$(MAKE) -f CMakeFiles/test_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_aes_byte_transition_algorithm.dir/src/column_pattern_generator.cc.o
	$(MAKE) -f CMakeFiles/test_all_small_aes_column_transitions.dir/build.make CMakeFiles/test_all_small_aes_column_transitions.dir/src/column_pattern_generator.cc.o
	$(MAKE) -f CMakeFiles/test_all_aes_column_transitions.dir/build.make CMakeFiles/test_all_aes_column_transitions.dir/src/column_pattern_generator.cc.o
	$(MAKE) -f CMakeFiles/transition_matrix.dir/build.make CMakeFiles/transition_matrix.dir/src/column_pattern_generator.cc.o
	$(MAKE) -f CMakeFiles/test_all_aes_byte_transitions.dir/build.make CMakeFiles/test_all_aes_byte_transitions.dir/src/column_pattern_generator.cc.o
	$(MAKE) -f CMakeFiles/test_small_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_small_aes_byte_transition_algorithm.dir/src/column_pattern_generator.cc.o
	$(MAKE) -f CMakeFiles/test_many_small_aes_column_transitions.dir/build.make CMakeFiles/test_many_small_aes_column_transitions.dir/src/column_pattern_generator.cc.o
	$(MAKE) -f CMakeFiles/test_all_small_aes_byte_transitions.dir/build.make CMakeFiles/test_all_small_aes_byte_transitions.dir/src/column_pattern_generator.cc.o
.PHONY : src/column_pattern_generator.cc.o

src/column_pattern_generator.i: src/column_pattern_generator.cc.i

.PHONY : src/column_pattern_generator.i

# target to preprocess a source file
src/column_pattern_generator.cc.i:
	$(MAKE) -f CMakeFiles/test_byte_pattern_generator.dir/build.make CMakeFiles/test_byte_pattern_generator.dir/src/column_pattern_generator.cc.i
	$(MAKE) -f CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/src/column_pattern_generator.cc.i
	$(MAKE) -f CMakeFiles/test_many_aes_column_transitions.dir/build.make CMakeFiles/test_many_aes_column_transitions.dir/src/column_pattern_generator.cc.i
	$(MAKE) -f CMakeFiles/test_aes_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_column_transition_algorithm.dir/src/column_pattern_generator.cc.i
	$(MAKE) -f CMakeFiles/test_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_aes_byte_transition_algorithm.dir/src/column_pattern_generator.cc.i
	$(MAKE) -f CMakeFiles/test_all_small_aes_column_transitions.dir/build.make CMakeFiles/test_all_small_aes_column_transitions.dir/src/column_pattern_generator.cc.i
	$(MAKE) -f CMakeFiles/test_all_aes_column_transitions.dir/build.make CMakeFiles/test_all_aes_column_transitions.dir/src/column_pattern_generator.cc.i
	$(MAKE) -f CMakeFiles/transition_matrix.dir/build.make CMakeFiles/transition_matrix.dir/src/column_pattern_generator.cc.i
	$(MAKE) -f CMakeFiles/test_all_aes_byte_transitions.dir/build.make CMakeFiles/test_all_aes_byte_transitions.dir/src/column_pattern_generator.cc.i
	$(MAKE) -f CMakeFiles/test_small_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_small_aes_byte_transition_algorithm.dir/src/column_pattern_generator.cc.i
	$(MAKE) -f CMakeFiles/test_many_small_aes_column_transitions.dir/build.make CMakeFiles/test_many_small_aes_column_transitions.dir/src/column_pattern_generator.cc.i
	$(MAKE) -f CMakeFiles/test_all_small_aes_byte_transitions.dir/build.make CMakeFiles/test_all_small_aes_byte_transitions.dir/src/column_pattern_generator.cc.i
.PHONY : src/column_pattern_generator.cc.i

src/column_pattern_generator.s: src/column_pattern_generator.cc.s

.PHONY : src/column_pattern_generator.s

# target to generate assembly for a file
src/column_pattern_generator.cc.s:
	$(MAKE) -f CMakeFiles/test_byte_pattern_generator.dir/build.make CMakeFiles/test_byte_pattern_generator.dir/src/column_pattern_generator.cc.s
	$(MAKE) -f CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/src/column_pattern_generator.cc.s
	$(MAKE) -f CMakeFiles/test_many_aes_column_transitions.dir/build.make CMakeFiles/test_many_aes_column_transitions.dir/src/column_pattern_generator.cc.s
	$(MAKE) -f CMakeFiles/test_aes_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_column_transition_algorithm.dir/src/column_pattern_generator.cc.s
	$(MAKE) -f CMakeFiles/test_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_aes_byte_transition_algorithm.dir/src/column_pattern_generator.cc.s
	$(MAKE) -f CMakeFiles/test_all_small_aes_column_transitions.dir/build.make CMakeFiles/test_all_small_aes_column_transitions.dir/src/column_pattern_generator.cc.s
	$(MAKE) -f CMakeFiles/test_all_aes_column_transitions.dir/build.make CMakeFiles/test_all_aes_column_transitions.dir/src/column_pattern_generator.cc.s
	$(MAKE) -f CMakeFiles/transition_matrix.dir/build.make CMakeFiles/transition_matrix.dir/src/column_pattern_generator.cc.s
	$(MAKE) -f CMakeFiles/test_all_aes_byte_transitions.dir/build.make CMakeFiles/test_all_aes_byte_transitions.dir/src/column_pattern_generator.cc.s
	$(MAKE) -f CMakeFiles/test_small_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_small_aes_byte_transition_algorithm.dir/src/column_pattern_generator.cc.s
	$(MAKE) -f CMakeFiles/test_many_small_aes_column_transitions.dir/build.make CMakeFiles/test_many_small_aes_column_transitions.dir/src/column_pattern_generator.cc.s
	$(MAKE) -f CMakeFiles/test_all_small_aes_byte_transitions.dir/build.make CMakeFiles/test_all_small_aes_byte_transitions.dir/src/column_pattern_generator.cc.s
.PHONY : src/column_pattern_generator.cc.s

src/small_aes_byte_transition_algorithm.o: src/small_aes_byte_transition_algorithm.cc.o

.PHONY : src/small_aes_byte_transition_algorithm.o

# target to build an object file
src/small_aes_byte_transition_algorithm.cc.o:
	$(MAKE) -f CMakeFiles/test_byte_pattern_generator.dir/build.make CMakeFiles/test_byte_pattern_generator.dir/src/small_aes_byte_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/src/small_aes_byte_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/test_many_aes_column_transitions.dir/build.make CMakeFiles/test_many_aes_column_transitions.dir/src/small_aes_byte_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/test_aes_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_column_transition_algorithm.dir/src/small_aes_byte_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/test_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_aes_byte_transition_algorithm.dir/src/small_aes_byte_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/test_all_small_aes_column_transitions.dir/build.make CMakeFiles/test_all_small_aes_column_transitions.dir/src/small_aes_byte_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/test_all_aes_column_transitions.dir/build.make CMakeFiles/test_all_aes_column_transitions.dir/src/small_aes_byte_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/transition_matrix.dir/build.make CMakeFiles/transition_matrix.dir/src/small_aes_byte_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/test_all_aes_byte_transitions.dir/build.make CMakeFiles/test_all_aes_byte_transitions.dir/src/small_aes_byte_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/test_small_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_small_aes_byte_transition_algorithm.dir/src/small_aes_byte_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/test_many_small_aes_column_transitions.dir/build.make CMakeFiles/test_many_small_aes_column_transitions.dir/src/small_aes_byte_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/test_all_small_aes_byte_transitions.dir/build.make CMakeFiles/test_all_small_aes_byte_transitions.dir/src/small_aes_byte_transition_algorithm.cc.o
.PHONY : src/small_aes_byte_transition_algorithm.cc.o

src/small_aes_byte_transition_algorithm.i: src/small_aes_byte_transition_algorithm.cc.i

.PHONY : src/small_aes_byte_transition_algorithm.i

# target to preprocess a source file
src/small_aes_byte_transition_algorithm.cc.i:
	$(MAKE) -f CMakeFiles/test_byte_pattern_generator.dir/build.make CMakeFiles/test_byte_pattern_generator.dir/src/small_aes_byte_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/src/small_aes_byte_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/test_many_aes_column_transitions.dir/build.make CMakeFiles/test_many_aes_column_transitions.dir/src/small_aes_byte_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/test_aes_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_column_transition_algorithm.dir/src/small_aes_byte_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/test_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_aes_byte_transition_algorithm.dir/src/small_aes_byte_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/test_all_small_aes_column_transitions.dir/build.make CMakeFiles/test_all_small_aes_column_transitions.dir/src/small_aes_byte_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/test_all_aes_column_transitions.dir/build.make CMakeFiles/test_all_aes_column_transitions.dir/src/small_aes_byte_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/transition_matrix.dir/build.make CMakeFiles/transition_matrix.dir/src/small_aes_byte_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/test_all_aes_byte_transitions.dir/build.make CMakeFiles/test_all_aes_byte_transitions.dir/src/small_aes_byte_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/test_small_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_small_aes_byte_transition_algorithm.dir/src/small_aes_byte_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/test_many_small_aes_column_transitions.dir/build.make CMakeFiles/test_many_small_aes_column_transitions.dir/src/small_aes_byte_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/test_all_small_aes_byte_transitions.dir/build.make CMakeFiles/test_all_small_aes_byte_transitions.dir/src/small_aes_byte_transition_algorithm.cc.i
.PHONY : src/small_aes_byte_transition_algorithm.cc.i

src/small_aes_byte_transition_algorithm.s: src/small_aes_byte_transition_algorithm.cc.s

.PHONY : src/small_aes_byte_transition_algorithm.s

# target to generate assembly for a file
src/small_aes_byte_transition_algorithm.cc.s:
	$(MAKE) -f CMakeFiles/test_byte_pattern_generator.dir/build.make CMakeFiles/test_byte_pattern_generator.dir/src/small_aes_byte_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/src/small_aes_byte_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/test_many_aes_column_transitions.dir/build.make CMakeFiles/test_many_aes_column_transitions.dir/src/small_aes_byte_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/test_aes_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_column_transition_algorithm.dir/src/small_aes_byte_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/test_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_aes_byte_transition_algorithm.dir/src/small_aes_byte_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/test_all_small_aes_column_transitions.dir/build.make CMakeFiles/test_all_small_aes_column_transitions.dir/src/small_aes_byte_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/test_all_aes_column_transitions.dir/build.make CMakeFiles/test_all_aes_column_transitions.dir/src/small_aes_byte_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/transition_matrix.dir/build.make CMakeFiles/transition_matrix.dir/src/small_aes_byte_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/test_all_aes_byte_transitions.dir/build.make CMakeFiles/test_all_aes_byte_transitions.dir/src/small_aes_byte_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/test_small_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_small_aes_byte_transition_algorithm.dir/src/small_aes_byte_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/test_many_small_aes_column_transitions.dir/build.make CMakeFiles/test_many_small_aes_column_transitions.dir/src/small_aes_byte_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/test_all_small_aes_byte_transitions.dir/build.make CMakeFiles/test_all_small_aes_byte_transitions.dir/src/small_aes_byte_transition_algorithm.cc.s
.PHONY : src/small_aes_byte_transition_algorithm.cc.s

src/small_aes_column_transition_algorithm.o: src/small_aes_column_transition_algorithm.cc.o

.PHONY : src/small_aes_column_transition_algorithm.o

# target to build an object file
src/small_aes_column_transition_algorithm.cc.o:
	$(MAKE) -f CMakeFiles/test_byte_pattern_generator.dir/build.make CMakeFiles/test_byte_pattern_generator.dir/src/small_aes_column_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/src/small_aes_column_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/test_many_aes_column_transitions.dir/build.make CMakeFiles/test_many_aes_column_transitions.dir/src/small_aes_column_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/test_aes_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_column_transition_algorithm.dir/src/small_aes_column_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/test_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_aes_byte_transition_algorithm.dir/src/small_aes_column_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/test_all_small_aes_column_transitions.dir/build.make CMakeFiles/test_all_small_aes_column_transitions.dir/src/small_aes_column_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/test_all_aes_column_transitions.dir/build.make CMakeFiles/test_all_aes_column_transitions.dir/src/small_aes_column_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/transition_matrix.dir/build.make CMakeFiles/transition_matrix.dir/src/small_aes_column_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/test_all_aes_byte_transitions.dir/build.make CMakeFiles/test_all_aes_byte_transitions.dir/src/small_aes_column_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/test_small_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_small_aes_byte_transition_algorithm.dir/src/small_aes_column_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/test_many_small_aes_column_transitions.dir/build.make CMakeFiles/test_many_small_aes_column_transitions.dir/src/small_aes_column_transition_algorithm.cc.o
	$(MAKE) -f CMakeFiles/test_all_small_aes_byte_transitions.dir/build.make CMakeFiles/test_all_small_aes_byte_transitions.dir/src/small_aes_column_transition_algorithm.cc.o
.PHONY : src/small_aes_column_transition_algorithm.cc.o

src/small_aes_column_transition_algorithm.i: src/small_aes_column_transition_algorithm.cc.i

.PHONY : src/small_aes_column_transition_algorithm.i

# target to preprocess a source file
src/small_aes_column_transition_algorithm.cc.i:
	$(MAKE) -f CMakeFiles/test_byte_pattern_generator.dir/build.make CMakeFiles/test_byte_pattern_generator.dir/src/small_aes_column_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/src/small_aes_column_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/test_many_aes_column_transitions.dir/build.make CMakeFiles/test_many_aes_column_transitions.dir/src/small_aes_column_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/test_aes_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_column_transition_algorithm.dir/src/small_aes_column_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/test_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_aes_byte_transition_algorithm.dir/src/small_aes_column_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/test_all_small_aes_column_transitions.dir/build.make CMakeFiles/test_all_small_aes_column_transitions.dir/src/small_aes_column_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/test_all_aes_column_transitions.dir/build.make CMakeFiles/test_all_aes_column_transitions.dir/src/small_aes_column_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/transition_matrix.dir/build.make CMakeFiles/transition_matrix.dir/src/small_aes_column_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/test_all_aes_byte_transitions.dir/build.make CMakeFiles/test_all_aes_byte_transitions.dir/src/small_aes_column_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/test_small_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_small_aes_byte_transition_algorithm.dir/src/small_aes_column_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/test_many_small_aes_column_transitions.dir/build.make CMakeFiles/test_many_small_aes_column_transitions.dir/src/small_aes_column_transition_algorithm.cc.i
	$(MAKE) -f CMakeFiles/test_all_small_aes_byte_transitions.dir/build.make CMakeFiles/test_all_small_aes_byte_transitions.dir/src/small_aes_column_transition_algorithm.cc.i
.PHONY : src/small_aes_column_transition_algorithm.cc.i

src/small_aes_column_transition_algorithm.s: src/small_aes_column_transition_algorithm.cc.s

.PHONY : src/small_aes_column_transition_algorithm.s

# target to generate assembly for a file
src/small_aes_column_transition_algorithm.cc.s:
	$(MAKE) -f CMakeFiles/test_byte_pattern_generator.dir/build.make CMakeFiles/test_byte_pattern_generator.dir/src/small_aes_column_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/src/small_aes_column_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/test_many_aes_column_transitions.dir/build.make CMakeFiles/test_many_aes_column_transitions.dir/src/small_aes_column_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/test_aes_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_column_transition_algorithm.dir/src/small_aes_column_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/test_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_aes_byte_transition_algorithm.dir/src/small_aes_column_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/test_all_small_aes_column_transitions.dir/build.make CMakeFiles/test_all_small_aes_column_transitions.dir/src/small_aes_column_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/test_all_aes_column_transitions.dir/build.make CMakeFiles/test_all_aes_column_transitions.dir/src/small_aes_column_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/transition_matrix.dir/build.make CMakeFiles/transition_matrix.dir/src/small_aes_column_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/test_all_aes_byte_transitions.dir/build.make CMakeFiles/test_all_aes_byte_transitions.dir/src/small_aes_column_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/test_small_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_small_aes_byte_transition_algorithm.dir/src/small_aes_column_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/test_many_small_aes_column_transitions.dir/build.make CMakeFiles/test_many_small_aes_column_transitions.dir/src/small_aes_column_transition_algorithm.cc.s
	$(MAKE) -f CMakeFiles/test_all_small_aes_byte_transitions.dir/build.make CMakeFiles/test_all_small_aes_byte_transitions.dir/src/small_aes_column_transition_algorithm.cc.s
.PHONY : src/small_aes_column_transition_algorithm.cc.s

src/util.o: src/util.cc.o

.PHONY : src/util.o

# target to build an object file
src/util.cc.o:
	$(MAKE) -f CMakeFiles/test_byte_pattern_generator.dir/build.make CMakeFiles/test_byte_pattern_generator.dir/src/util.cc.o
	$(MAKE) -f CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/src/util.cc.o
	$(MAKE) -f CMakeFiles/test_many_aes_column_transitions.dir/build.make CMakeFiles/test_many_aes_column_transitions.dir/src/util.cc.o
	$(MAKE) -f CMakeFiles/test_aes_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_column_transition_algorithm.dir/src/util.cc.o
	$(MAKE) -f CMakeFiles/test_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_aes_byte_transition_algorithm.dir/src/util.cc.o
	$(MAKE) -f CMakeFiles/test_all_small_aes_column_transitions.dir/build.make CMakeFiles/test_all_small_aes_column_transitions.dir/src/util.cc.o
	$(MAKE) -f CMakeFiles/test_all_aes_column_transitions.dir/build.make CMakeFiles/test_all_aes_column_transitions.dir/src/util.cc.o
	$(MAKE) -f CMakeFiles/transition_matrix.dir/build.make CMakeFiles/transition_matrix.dir/src/util.cc.o
	$(MAKE) -f CMakeFiles/test_all_aes_byte_transitions.dir/build.make CMakeFiles/test_all_aes_byte_transitions.dir/src/util.cc.o
	$(MAKE) -f CMakeFiles/test_small_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_small_aes_byte_transition_algorithm.dir/src/util.cc.o
	$(MAKE) -f CMakeFiles/test_many_small_aes_column_transitions.dir/build.make CMakeFiles/test_many_small_aes_column_transitions.dir/src/util.cc.o
	$(MAKE) -f CMakeFiles/test_all_small_aes_byte_transitions.dir/build.make CMakeFiles/test_all_small_aes_byte_transitions.dir/src/util.cc.o
.PHONY : src/util.cc.o

src/util.i: src/util.cc.i

.PHONY : src/util.i

# target to preprocess a source file
src/util.cc.i:
	$(MAKE) -f CMakeFiles/test_byte_pattern_generator.dir/build.make CMakeFiles/test_byte_pattern_generator.dir/src/util.cc.i
	$(MAKE) -f CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/src/util.cc.i
	$(MAKE) -f CMakeFiles/test_many_aes_column_transitions.dir/build.make CMakeFiles/test_many_aes_column_transitions.dir/src/util.cc.i
	$(MAKE) -f CMakeFiles/test_aes_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_column_transition_algorithm.dir/src/util.cc.i
	$(MAKE) -f CMakeFiles/test_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_aes_byte_transition_algorithm.dir/src/util.cc.i
	$(MAKE) -f CMakeFiles/test_all_small_aes_column_transitions.dir/build.make CMakeFiles/test_all_small_aes_column_transitions.dir/src/util.cc.i
	$(MAKE) -f CMakeFiles/test_all_aes_column_transitions.dir/build.make CMakeFiles/test_all_aes_column_transitions.dir/src/util.cc.i
	$(MAKE) -f CMakeFiles/transition_matrix.dir/build.make CMakeFiles/transition_matrix.dir/src/util.cc.i
	$(MAKE) -f CMakeFiles/test_all_aes_byte_transitions.dir/build.make CMakeFiles/test_all_aes_byte_transitions.dir/src/util.cc.i
	$(MAKE) -f CMakeFiles/test_small_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_small_aes_byte_transition_algorithm.dir/src/util.cc.i
	$(MAKE) -f CMakeFiles/test_many_small_aes_column_transitions.dir/build.make CMakeFiles/test_many_small_aes_column_transitions.dir/src/util.cc.i
	$(MAKE) -f CMakeFiles/test_all_small_aes_byte_transitions.dir/build.make CMakeFiles/test_all_small_aes_byte_transitions.dir/src/util.cc.i
.PHONY : src/util.cc.i

src/util.s: src/util.cc.s

.PHONY : src/util.s

# target to generate assembly for a file
src/util.cc.s:
	$(MAKE) -f CMakeFiles/test_byte_pattern_generator.dir/build.make CMakeFiles/test_byte_pattern_generator.dir/src/util.cc.s
	$(MAKE) -f CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/src/util.cc.s
	$(MAKE) -f CMakeFiles/test_many_aes_column_transitions.dir/build.make CMakeFiles/test_many_aes_column_transitions.dir/src/util.cc.s
	$(MAKE) -f CMakeFiles/test_aes_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_column_transition_algorithm.dir/src/util.cc.s
	$(MAKE) -f CMakeFiles/test_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_aes_byte_transition_algorithm.dir/src/util.cc.s
	$(MAKE) -f CMakeFiles/test_all_small_aes_column_transitions.dir/build.make CMakeFiles/test_all_small_aes_column_transitions.dir/src/util.cc.s
	$(MAKE) -f CMakeFiles/test_all_aes_column_transitions.dir/build.make CMakeFiles/test_all_aes_column_transitions.dir/src/util.cc.s
	$(MAKE) -f CMakeFiles/transition_matrix.dir/build.make CMakeFiles/transition_matrix.dir/src/util.cc.s
	$(MAKE) -f CMakeFiles/test_all_aes_byte_transitions.dir/build.make CMakeFiles/test_all_aes_byte_transitions.dir/src/util.cc.s
	$(MAKE) -f CMakeFiles/test_small_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_small_aes_byte_transition_algorithm.dir/src/util.cc.s
	$(MAKE) -f CMakeFiles/test_many_small_aes_column_transitions.dir/build.make CMakeFiles/test_many_small_aes_column_transitions.dir/src/util.cc.s
	$(MAKE) -f CMakeFiles/test_all_small_aes_byte_transitions.dir/build.make CMakeFiles/test_all_small_aes_byte_transitions.dir/src/util.cc.s
.PHONY : src/util.cc.s

tests/test_aes_byte_transition_algorithm.o: tests/test_aes_byte_transition_algorithm.cc.o

.PHONY : tests/test_aes_byte_transition_algorithm.o

# target to build an object file
tests/test_aes_byte_transition_algorithm.cc.o:
	$(MAKE) -f CMakeFiles/test_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_aes_byte_transition_algorithm.dir/tests/test_aes_byte_transition_algorithm.cc.o
.PHONY : tests/test_aes_byte_transition_algorithm.cc.o

tests/test_aes_byte_transition_algorithm.i: tests/test_aes_byte_transition_algorithm.cc.i

.PHONY : tests/test_aes_byte_transition_algorithm.i

# target to preprocess a source file
tests/test_aes_byte_transition_algorithm.cc.i:
	$(MAKE) -f CMakeFiles/test_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_aes_byte_transition_algorithm.dir/tests/test_aes_byte_transition_algorithm.cc.i
.PHONY : tests/test_aes_byte_transition_algorithm.cc.i

tests/test_aes_byte_transition_algorithm.s: tests/test_aes_byte_transition_algorithm.cc.s

.PHONY : tests/test_aes_byte_transition_algorithm.s

# target to generate assembly for a file
tests/test_aes_byte_transition_algorithm.cc.s:
	$(MAKE) -f CMakeFiles/test_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_aes_byte_transition_algorithm.dir/tests/test_aes_byte_transition_algorithm.cc.s
.PHONY : tests/test_aes_byte_transition_algorithm.cc.s

tests/test_aes_column_transition_algorithm.o: tests/test_aes_column_transition_algorithm.cc.o

.PHONY : tests/test_aes_column_transition_algorithm.o

# target to build an object file
tests/test_aes_column_transition_algorithm.cc.o:
	$(MAKE) -f CMakeFiles/test_aes_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_column_transition_algorithm.dir/tests/test_aes_column_transition_algorithm.cc.o
.PHONY : tests/test_aes_column_transition_algorithm.cc.o

tests/test_aes_column_transition_algorithm.i: tests/test_aes_column_transition_algorithm.cc.i

.PHONY : tests/test_aes_column_transition_algorithm.i

# target to preprocess a source file
tests/test_aes_column_transition_algorithm.cc.i:
	$(MAKE) -f CMakeFiles/test_aes_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_column_transition_algorithm.dir/tests/test_aes_column_transition_algorithm.cc.i
.PHONY : tests/test_aes_column_transition_algorithm.cc.i

tests/test_aes_column_transition_algorithm.s: tests/test_aes_column_transition_algorithm.cc.s

.PHONY : tests/test_aes_column_transition_algorithm.s

# target to generate assembly for a file
tests/test_aes_column_transition_algorithm.cc.s:
	$(MAKE) -f CMakeFiles/test_aes_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_column_transition_algorithm.dir/tests/test_aes_column_transition_algorithm.cc.s
.PHONY : tests/test_aes_column_transition_algorithm.cc.s

tests/test_aes_row_and_column_transition_algorithm.o: tests/test_aes_row_and_column_transition_algorithm.cc.o

.PHONY : tests/test_aes_row_and_column_transition_algorithm.o

# target to build an object file
tests/test_aes_row_and_column_transition_algorithm.cc.o:
	$(MAKE) -f CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/tests/test_aes_row_and_column_transition_algorithm.cc.o
.PHONY : tests/test_aes_row_and_column_transition_algorithm.cc.o

tests/test_aes_row_and_column_transition_algorithm.i: tests/test_aes_row_and_column_transition_algorithm.cc.i

.PHONY : tests/test_aes_row_and_column_transition_algorithm.i

# target to preprocess a source file
tests/test_aes_row_and_column_transition_algorithm.cc.i:
	$(MAKE) -f CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/tests/test_aes_row_and_column_transition_algorithm.cc.i
.PHONY : tests/test_aes_row_and_column_transition_algorithm.cc.i

tests/test_aes_row_and_column_transition_algorithm.s: tests/test_aes_row_and_column_transition_algorithm.cc.s

.PHONY : tests/test_aes_row_and_column_transition_algorithm.s

# target to generate assembly for a file
tests/test_aes_row_and_column_transition_algorithm.cc.s:
	$(MAKE) -f CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/build.make CMakeFiles/test_aes_row_and_column_transition_algorithm.dir/tests/test_aes_row_and_column_transition_algorithm.cc.s
.PHONY : tests/test_aes_row_and_column_transition_algorithm.cc.s

tests/test_all_aes_byte_transitions.o: tests/test_all_aes_byte_transitions.cc.o

.PHONY : tests/test_all_aes_byte_transitions.o

# target to build an object file
tests/test_all_aes_byte_transitions.cc.o:
	$(MAKE) -f CMakeFiles/test_all_aes_byte_transitions.dir/build.make CMakeFiles/test_all_aes_byte_transitions.dir/tests/test_all_aes_byte_transitions.cc.o
.PHONY : tests/test_all_aes_byte_transitions.cc.o

tests/test_all_aes_byte_transitions.i: tests/test_all_aes_byte_transitions.cc.i

.PHONY : tests/test_all_aes_byte_transitions.i

# target to preprocess a source file
tests/test_all_aes_byte_transitions.cc.i:
	$(MAKE) -f CMakeFiles/test_all_aes_byte_transitions.dir/build.make CMakeFiles/test_all_aes_byte_transitions.dir/tests/test_all_aes_byte_transitions.cc.i
.PHONY : tests/test_all_aes_byte_transitions.cc.i

tests/test_all_aes_byte_transitions.s: tests/test_all_aes_byte_transitions.cc.s

.PHONY : tests/test_all_aes_byte_transitions.s

# target to generate assembly for a file
tests/test_all_aes_byte_transitions.cc.s:
	$(MAKE) -f CMakeFiles/test_all_aes_byte_transitions.dir/build.make CMakeFiles/test_all_aes_byte_transitions.dir/tests/test_all_aes_byte_transitions.cc.s
.PHONY : tests/test_all_aes_byte_transitions.cc.s

tests/test_all_aes_column_transitions.o: tests/test_all_aes_column_transitions.cc.o

.PHONY : tests/test_all_aes_column_transitions.o

# target to build an object file
tests/test_all_aes_column_transitions.cc.o:
	$(MAKE) -f CMakeFiles/test_all_aes_column_transitions.dir/build.make CMakeFiles/test_all_aes_column_transitions.dir/tests/test_all_aes_column_transitions.cc.o
.PHONY : tests/test_all_aes_column_transitions.cc.o

tests/test_all_aes_column_transitions.i: tests/test_all_aes_column_transitions.cc.i

.PHONY : tests/test_all_aes_column_transitions.i

# target to preprocess a source file
tests/test_all_aes_column_transitions.cc.i:
	$(MAKE) -f CMakeFiles/test_all_aes_column_transitions.dir/build.make CMakeFiles/test_all_aes_column_transitions.dir/tests/test_all_aes_column_transitions.cc.i
.PHONY : tests/test_all_aes_column_transitions.cc.i

tests/test_all_aes_column_transitions.s: tests/test_all_aes_column_transitions.cc.s

.PHONY : tests/test_all_aes_column_transitions.s

# target to generate assembly for a file
tests/test_all_aes_column_transitions.cc.s:
	$(MAKE) -f CMakeFiles/test_all_aes_column_transitions.dir/build.make CMakeFiles/test_all_aes_column_transitions.dir/tests/test_all_aes_column_transitions.cc.s
.PHONY : tests/test_all_aes_column_transitions.cc.s

tests/test_all_small_aes_byte_transitions.o: tests/test_all_small_aes_byte_transitions.cc.o

.PHONY : tests/test_all_small_aes_byte_transitions.o

# target to build an object file
tests/test_all_small_aes_byte_transitions.cc.o:
	$(MAKE) -f CMakeFiles/test_all_small_aes_byte_transitions.dir/build.make CMakeFiles/test_all_small_aes_byte_transitions.dir/tests/test_all_small_aes_byte_transitions.cc.o
.PHONY : tests/test_all_small_aes_byte_transitions.cc.o

tests/test_all_small_aes_byte_transitions.i: tests/test_all_small_aes_byte_transitions.cc.i

.PHONY : tests/test_all_small_aes_byte_transitions.i

# target to preprocess a source file
tests/test_all_small_aes_byte_transitions.cc.i:
	$(MAKE) -f CMakeFiles/test_all_small_aes_byte_transitions.dir/build.make CMakeFiles/test_all_small_aes_byte_transitions.dir/tests/test_all_small_aes_byte_transitions.cc.i
.PHONY : tests/test_all_small_aes_byte_transitions.cc.i

tests/test_all_small_aes_byte_transitions.s: tests/test_all_small_aes_byte_transitions.cc.s

.PHONY : tests/test_all_small_aes_byte_transitions.s

# target to generate assembly for a file
tests/test_all_small_aes_byte_transitions.cc.s:
	$(MAKE) -f CMakeFiles/test_all_small_aes_byte_transitions.dir/build.make CMakeFiles/test_all_small_aes_byte_transitions.dir/tests/test_all_small_aes_byte_transitions.cc.s
.PHONY : tests/test_all_small_aes_byte_transitions.cc.s

tests/test_all_small_aes_column_transitions.o: tests/test_all_small_aes_column_transitions.cc.o

.PHONY : tests/test_all_small_aes_column_transitions.o

# target to build an object file
tests/test_all_small_aes_column_transitions.cc.o:
	$(MAKE) -f CMakeFiles/test_all_small_aes_column_transitions.dir/build.make CMakeFiles/test_all_small_aes_column_transitions.dir/tests/test_all_small_aes_column_transitions.cc.o
.PHONY : tests/test_all_small_aes_column_transitions.cc.o

tests/test_all_small_aes_column_transitions.i: tests/test_all_small_aes_column_transitions.cc.i

.PHONY : tests/test_all_small_aes_column_transitions.i

# target to preprocess a source file
tests/test_all_small_aes_column_transitions.cc.i:
	$(MAKE) -f CMakeFiles/test_all_small_aes_column_transitions.dir/build.make CMakeFiles/test_all_small_aes_column_transitions.dir/tests/test_all_small_aes_column_transitions.cc.i
.PHONY : tests/test_all_small_aes_column_transitions.cc.i

tests/test_all_small_aes_column_transitions.s: tests/test_all_small_aes_column_transitions.cc.s

.PHONY : tests/test_all_small_aes_column_transitions.s

# target to generate assembly for a file
tests/test_all_small_aes_column_transitions.cc.s:
	$(MAKE) -f CMakeFiles/test_all_small_aes_column_transitions.dir/build.make CMakeFiles/test_all_small_aes_column_transitions.dir/tests/test_all_small_aes_column_transitions.cc.s
.PHONY : tests/test_all_small_aes_column_transitions.cc.s

tests/test_byte_pattern_generator.o: tests/test_byte_pattern_generator.cc.o

.PHONY : tests/test_byte_pattern_generator.o

# target to build an object file
tests/test_byte_pattern_generator.cc.o:
	$(MAKE) -f CMakeFiles/test_byte_pattern_generator.dir/build.make CMakeFiles/test_byte_pattern_generator.dir/tests/test_byte_pattern_generator.cc.o
.PHONY : tests/test_byte_pattern_generator.cc.o

tests/test_byte_pattern_generator.i: tests/test_byte_pattern_generator.cc.i

.PHONY : tests/test_byte_pattern_generator.i

# target to preprocess a source file
tests/test_byte_pattern_generator.cc.i:
	$(MAKE) -f CMakeFiles/test_byte_pattern_generator.dir/build.make CMakeFiles/test_byte_pattern_generator.dir/tests/test_byte_pattern_generator.cc.i
.PHONY : tests/test_byte_pattern_generator.cc.i

tests/test_byte_pattern_generator.s: tests/test_byte_pattern_generator.cc.s

.PHONY : tests/test_byte_pattern_generator.s

# target to generate assembly for a file
tests/test_byte_pattern_generator.cc.s:
	$(MAKE) -f CMakeFiles/test_byte_pattern_generator.dir/build.make CMakeFiles/test_byte_pattern_generator.dir/tests/test_byte_pattern_generator.cc.s
.PHONY : tests/test_byte_pattern_generator.cc.s

tests/test_many_aes_column_transitions.o: tests/test_many_aes_column_transitions.cc.o

.PHONY : tests/test_many_aes_column_transitions.o

# target to build an object file
tests/test_many_aes_column_transitions.cc.o:
	$(MAKE) -f CMakeFiles/test_many_aes_column_transitions.dir/build.make CMakeFiles/test_many_aes_column_transitions.dir/tests/test_many_aes_column_transitions.cc.o
.PHONY : tests/test_many_aes_column_transitions.cc.o

tests/test_many_aes_column_transitions.i: tests/test_many_aes_column_transitions.cc.i

.PHONY : tests/test_many_aes_column_transitions.i

# target to preprocess a source file
tests/test_many_aes_column_transitions.cc.i:
	$(MAKE) -f CMakeFiles/test_many_aes_column_transitions.dir/build.make CMakeFiles/test_many_aes_column_transitions.dir/tests/test_many_aes_column_transitions.cc.i
.PHONY : tests/test_many_aes_column_transitions.cc.i

tests/test_many_aes_column_transitions.s: tests/test_many_aes_column_transitions.cc.s

.PHONY : tests/test_many_aes_column_transitions.s

# target to generate assembly for a file
tests/test_many_aes_column_transitions.cc.s:
	$(MAKE) -f CMakeFiles/test_many_aes_column_transitions.dir/build.make CMakeFiles/test_many_aes_column_transitions.dir/tests/test_many_aes_column_transitions.cc.s
.PHONY : tests/test_many_aes_column_transitions.cc.s

tests/test_many_small_aes_column_transitions.o: tests/test_many_small_aes_column_transitions.cc.o

.PHONY : tests/test_many_small_aes_column_transitions.o

# target to build an object file
tests/test_many_small_aes_column_transitions.cc.o:
	$(MAKE) -f CMakeFiles/test_many_small_aes_column_transitions.dir/build.make CMakeFiles/test_many_small_aes_column_transitions.dir/tests/test_many_small_aes_column_transitions.cc.o
.PHONY : tests/test_many_small_aes_column_transitions.cc.o

tests/test_many_small_aes_column_transitions.i: tests/test_many_small_aes_column_transitions.cc.i

.PHONY : tests/test_many_small_aes_column_transitions.i

# target to preprocess a source file
tests/test_many_small_aes_column_transitions.cc.i:
	$(MAKE) -f CMakeFiles/test_many_small_aes_column_transitions.dir/build.make CMakeFiles/test_many_small_aes_column_transitions.dir/tests/test_many_small_aes_column_transitions.cc.i
.PHONY : tests/test_many_small_aes_column_transitions.cc.i

tests/test_many_small_aes_column_transitions.s: tests/test_many_small_aes_column_transitions.cc.s

.PHONY : tests/test_many_small_aes_column_transitions.s

# target to generate assembly for a file
tests/test_many_small_aes_column_transitions.cc.s:
	$(MAKE) -f CMakeFiles/test_many_small_aes_column_transitions.dir/build.make CMakeFiles/test_many_small_aes_column_transitions.dir/tests/test_many_small_aes_column_transitions.cc.s
.PHONY : tests/test_many_small_aes_column_transitions.cc.s

tests/test_small_aes_byte_transition_algorithm.o: tests/test_small_aes_byte_transition_algorithm.cc.o

.PHONY : tests/test_small_aes_byte_transition_algorithm.o

# target to build an object file
tests/test_small_aes_byte_transition_algorithm.cc.o:
	$(MAKE) -f CMakeFiles/test_small_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_small_aes_byte_transition_algorithm.dir/tests/test_small_aes_byte_transition_algorithm.cc.o
.PHONY : tests/test_small_aes_byte_transition_algorithm.cc.o

tests/test_small_aes_byte_transition_algorithm.i: tests/test_small_aes_byte_transition_algorithm.cc.i

.PHONY : tests/test_small_aes_byte_transition_algorithm.i

# target to preprocess a source file
tests/test_small_aes_byte_transition_algorithm.cc.i:
	$(MAKE) -f CMakeFiles/test_small_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_small_aes_byte_transition_algorithm.dir/tests/test_small_aes_byte_transition_algorithm.cc.i
.PHONY : tests/test_small_aes_byte_transition_algorithm.cc.i

tests/test_small_aes_byte_transition_algorithm.s: tests/test_small_aes_byte_transition_algorithm.cc.s

.PHONY : tests/test_small_aes_byte_transition_algorithm.s

# target to generate assembly for a file
tests/test_small_aes_byte_transition_algorithm.cc.s:
	$(MAKE) -f CMakeFiles/test_small_aes_byte_transition_algorithm.dir/build.make CMakeFiles/test_small_aes_byte_transition_algorithm.dir/tests/test_small_aes_byte_transition_algorithm.cc.s
.PHONY : tests/test_small_aes_byte_transition_algorithm.cc.s

tests/transition_matrix.o: tests/transition_matrix.cc.o

.PHONY : tests/transition_matrix.o

# target to build an object file
tests/transition_matrix.cc.o:
	$(MAKE) -f CMakeFiles/transition_matrix.dir/build.make CMakeFiles/transition_matrix.dir/tests/transition_matrix.cc.o
.PHONY : tests/transition_matrix.cc.o

tests/transition_matrix.i: tests/transition_matrix.cc.i

.PHONY : tests/transition_matrix.i

# target to preprocess a source file
tests/transition_matrix.cc.i:
	$(MAKE) -f CMakeFiles/transition_matrix.dir/build.make CMakeFiles/transition_matrix.dir/tests/transition_matrix.cc.i
.PHONY : tests/transition_matrix.cc.i

tests/transition_matrix.s: tests/transition_matrix.cc.s

.PHONY : tests/transition_matrix.s

# target to generate assembly for a file
tests/transition_matrix.cc.s:
	$(MAKE) -f CMakeFiles/transition_matrix.dir/build.make CMakeFiles/transition_matrix.dir/tests/transition_matrix.cc.s
.PHONY : tests/transition_matrix.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... test_byte_pattern_generator"
	@echo "... test_aes_row_and_column_transition_algorithm"
	@echo "... test_many_aes_column_transitions"
	@echo "... test_aes_column_transition_algorithm"
	@echo "... test_aes_byte_transition_algorithm"
	@echo "... test_all_small_aes_column_transitions"
	@echo "... test_all_aes_column_transitions"
	@echo "... transition_matrix"
	@echo "... test_all_aes_byte_transitions"
	@echo "... test_small_aes_byte_transition_algorithm"
	@echo "... test_many_small_aes_column_transitions"
	@echo "... edit_cache"
	@echo "... test_all_small_aes_byte_transitions"
	@echo "... src/aes_byte_transition_algorithm.o"
	@echo "... src/aes_byte_transition_algorithm.i"
	@echo "... src/aes_byte_transition_algorithm.s"
	@echo "... src/aes_column_transition_algorithm.o"
	@echo "... src/aes_column_transition_algorithm.i"
	@echo "... src/aes_column_transition_algorithm.s"
	@echo "... src/aes_row_and_column_transition_algorithm.o"
	@echo "... src/aes_row_and_column_transition_algorithm.i"
	@echo "... src/aes_row_and_column_transition_algorithm.s"
	@echo "... src/byte_pattern_generator.o"
	@echo "... src/byte_pattern_generator.i"
	@echo "... src/byte_pattern_generator.s"
	@echo "... src/column_pattern_generator.o"
	@echo "... src/column_pattern_generator.i"
	@echo "... src/column_pattern_generator.s"
	@echo "... src/small_aes_byte_transition_algorithm.o"
	@echo "... src/small_aes_byte_transition_algorithm.i"
	@echo "... src/small_aes_byte_transition_algorithm.s"
	@echo "... src/small_aes_column_transition_algorithm.o"
	@echo "... src/small_aes_column_transition_algorithm.i"
	@echo "... src/small_aes_column_transition_algorithm.s"
	@echo "... src/util.o"
	@echo "... src/util.i"
	@echo "... src/util.s"
	@echo "... tests/test_aes_byte_transition_algorithm.o"
	@echo "... tests/test_aes_byte_transition_algorithm.i"
	@echo "... tests/test_aes_byte_transition_algorithm.s"
	@echo "... tests/test_aes_column_transition_algorithm.o"
	@echo "... tests/test_aes_column_transition_algorithm.i"
	@echo "... tests/test_aes_column_transition_algorithm.s"
	@echo "... tests/test_aes_row_and_column_transition_algorithm.o"
	@echo "... tests/test_aes_row_and_column_transition_algorithm.i"
	@echo "... tests/test_aes_row_and_column_transition_algorithm.s"
	@echo "... tests/test_all_aes_byte_transitions.o"
	@echo "... tests/test_all_aes_byte_transitions.i"
	@echo "... tests/test_all_aes_byte_transitions.s"
	@echo "... tests/test_all_aes_column_transitions.o"
	@echo "... tests/test_all_aes_column_transitions.i"
	@echo "... tests/test_all_aes_column_transitions.s"
	@echo "... tests/test_all_small_aes_byte_transitions.o"
	@echo "... tests/test_all_small_aes_byte_transitions.i"
	@echo "... tests/test_all_small_aes_byte_transitions.s"
	@echo "... tests/test_all_small_aes_column_transitions.o"
	@echo "... tests/test_all_small_aes_column_transitions.i"
	@echo "... tests/test_all_small_aes_column_transitions.s"
	@echo "... tests/test_byte_pattern_generator.o"
	@echo "... tests/test_byte_pattern_generator.i"
	@echo "... tests/test_byte_pattern_generator.s"
	@echo "... tests/test_many_aes_column_transitions.o"
	@echo "... tests/test_many_aes_column_transitions.i"
	@echo "... tests/test_many_aes_column_transitions.s"
	@echo "... tests/test_many_small_aes_column_transitions.o"
	@echo "... tests/test_many_small_aes_column_transitions.i"
	@echo "... tests/test_many_small_aes_column_transitions.s"
	@echo "... tests/test_small_aes_byte_transition_algorithm.o"
	@echo "... tests/test_small_aes_byte_transition_algorithm.i"
	@echo "... tests/test_small_aes_byte_transition_algorithm.s"
	@echo "... tests/transition_matrix.o"
	@echo "... tests/transition_matrix.i"
	@echo "... tests/transition_matrix.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

